# Vector

In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5])

In [3]:
x

array([25,  2,  5])

In [7]:
len(x)

3

In [8]:
x.shape

(3,)

In [9]:
type(x)

numpy.ndarray

In [10]:
x[1]

2

# Vector Transpose

In [4]:
y = np.array([[25, 2, 5], [15, 7, 25]])
y

array([[25,  2,  5],
       [15,  7, 25]])

In [5]:
y.shape

(2, 3)

In [6]:
y_transpose = np.transpose(y)
y_transpose

array([[25, 15],
       [ 2,  7],
       [ 5, 25]])